name: Save atomic files every week

# on: 
#   schedule:
#     - cron: '0 0 * * 7' # run at midnight every Sunday

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'


jobs:
  run_the_bridge:
    # runs-on: ubuntu-latest
    uses: ./.github/workflows/bridge.yml
    # with:
    #       path: bridge/
  
  other_job:
    needs: run_the_bridge
    runs-on: ubuntu-latest
    steps:
      - name: Print directory tree
        run: tree


