name: Save atomic files every week

# on: 
#   schedule:
#     - cron: '0 0 * * 7' # run at midnight every Sunday

on:
  push:
    branches:
    - '*'

  pull_request:
    branches:
    - '*'


jobs:
  create_artifacts:
    uses: ./.github/workflows/bridge.yml
  
  zip_artifacts:
    needs: create_artifacts
    runs-on: ubuntu-latest
    steps:
      - name: Download atom data
        uses: actions/download-artifact@v2
        with:
          name: atom-data

      - name: Download comparison notebook
        uses: actions/download-artifact@v2
        with:
          name: Comparison Notebook

      - name: Zip files
        run: zip $(date +'%d_%b_%Y')  kurucz_cd23_chianti_H_He.h5 ref_data_compare_from_paths.html
        
      - name: Upload combined artifact
        uses: actions/upload-artifact@v2
        with:
          path: '*_*_*.zip'
      

  


